# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gio_hang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1217, 799)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 120, 221, 681))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: #C62828\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.mon_an = QtWidgets.QPushButton(Dialog)
        self.mon_an.setGeometry(QtCore.QRect(-10, 120, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mon_an.setFont(font)
        self.mon_an.setStyleSheet("")
        self.mon_an.setObjectName("mon_an")
        self.gio_hang = QtWidgets.QPushButton(Dialog)
        self.gio_hang.setGeometry(QtCore.QRect(-10, 210, 231, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.gio_hang.setFont(font)
        self.gio_hang.setStyleSheet("")
        self.gio_hang.setObjectName("gio_hang")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 91, 91))
        self.label_4.setStyleSheet("border-image: url(:/pic/logoss.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.tim_kiem = QtWidgets.QLineEdit(Dialog)
        self.tim_kiem.setGeometry(QtCore.QRect(360, 40, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tim_kiem.setFont(font)
        self.tim_kiem.setStyleSheet("QLineEdit {\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"    background-color: #f9f9f9;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid white;  /* vẫn là trắng khi focus */\n"
"}\n"
"")
        self.tim_kiem.setText("")
        self.tim_kiem.setObjectName("tim_kiem")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: transparent;  /* làm nền trong suốt nếu muốn */            /* tùy chỉnh cỡ chữ nếu cần */\n"
"    font-weight: bold;              /* chữ đậm */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1231, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #D32F2F")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 120, 1001, 681))
        self.label_6.setStyleSheet("background-color: rgb(255, 245, 225);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_55 = QtWidgets.QLabel(Dialog)
        self.label_55.setGeometry(QtCore.QRect(580, 150, 261, 61))
        self.label_55.setStyleSheet("QLabel {\n"
"    background-color: #d2b48c;  /* Nâu nhạt (beige) */\n"
"    color: #4e342e;              /* Nâu đậm cho chữ */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    border-radius: 12px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.label_55.setObjectName("label_55")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(260, 240, 921, 381))
        self.label_7.setStyleSheet("QLabel {\n"
"      background-color: #ffe5b4;  /* Nâu nhạt (beige) */\n"
"    color: black;\n"
" \n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(260, 640, 921, 131))
        self.label_8.setStyleSheet("QLabel {\n"
"      background-color: #ffe5b4;  /* Nâu nhạt (beige) */\n"
"    color: black;\n"
" \n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(280, 650, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.chuyen_khoan = QtWidgets.QPushButton(Dialog)
        self.chuyen_khoan.setGeometry(QtCore.QRect(720, 710, 141, 41))
        self.chuyen_khoan.setStyleSheet("QPushButton {\n"
"    background-color: #d2b48c;   /* Nâu nhạt (beige) */\n"
"    color: #4e342e;               /* Nâu đậm cho chữ */\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    border-radius: 12px;\n"
"    /* Văn bản button vốn đã canh giữa, \n"
"       nếu muốn chắc, có thể dùng text-align */\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Tuỳ chọn thêm hiệu ứng hover/pressed */\n"
"QPushButton:hover {\n"
"    background-color: #e0c2a0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #bfa284;\n"
"}\n"
"")
        self.chuyen_khoan.setObjectName("chuyen_khoan")
        self.tien_mat = QtWidgets.QPushButton(Dialog)
        self.tien_mat.setGeometry(QtCore.QRect(560, 710, 141, 41))
        self.tien_mat.setStyleSheet("QPushButton {\n"
"    background-color: #d2b48c;   /* Nâu nhạt (beige) */\n"
"    color: #4e342e;               /* Nâu đậm cho chữ */\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    border-radius: 12px;\n"
"    /* Văn bản button vốn đã canh giữa, \n"
"       nếu muốn chắc, có thể dùng text-align */\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Tuỳ chọn thêm hiệu ứng hover/pressed */\n"
"QPushButton:hover {\n"
"    background-color: #e0c2a0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #bfa284;\n"
"}\n"
"")
        self.tien_mat.setObjectName("tien_mat")
        self.xac_nhan = QtWidgets.QPushButton(Dialog)
        self.xac_nhan.setGeometry(QtCore.QRect(660, 650, 101, 41))
        self.xac_nhan.setStyleSheet("QPushButton {\n"
"    background-color: #d2b48c;   /* Nâu nhạt (beige) */\n"
"    color: #4e342e;               /* Nâu đậm cho chữ */\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    border-radius: 12px;\n"
"    /* Văn bản button vốn đã canh giữa, \n"
"       nếu muốn chắc, có thể dùng text-align */\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Tuỳ chọn thêm hiệu ứng hover/pressed */\n"
"QPushButton:hover {\n"
"    background-color: #e0c2a0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #bfa284;\n"
"}\n"
"")
        self.xac_nhan.setObjectName("xac_nhan")
        self.chon_ban = QtWidgets.QComboBox(Dialog)
        self.chon_ban.setGeometry(QtCore.QRect(1080, 260, 81, 31))
        self.chon_ban.setStyleSheet("    background-color: #d2b48c;   /* Nâu nhạt (beige) */\n"
"    color: #4e342e;               /* Nâu đậm cho chữ */\n"
"    border-radius: 12px;\n"
"    /* Văn bản button vốn đã canh giữa, \n"
"       nếu muốn chắc, có thể dùng text-align */\n"
"    text-align: center;\n"
"}\n"
"\n"
"")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.chon_ban.setFont(font)
        self.chon_ban.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.chon_ban.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chon_ban.setObjectName("chon_ban")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.chon_ban.addItem("")
        self.label_5.raise_()
        self.mon_an.raise_()
        self.gio_hang.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.tim_kiem.raise_()
        self.label_6.raise_()
        self.label_55.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.chuyen_khoan.raise_()
        self.tien_mat.raise_()
        self.xac_nhan.raise_()
        self.chon_ban.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mon_an.setText(_translate("Dialog", "🍰Menu món ăn "))
        self.gio_hang.setText(_translate("Dialog", "🛒Giỏ hàng"))
        self.tim_kiem.setPlaceholderText(_translate("Dialog", "Tìm kiếm..."))
        self.label_3.setText(_translate("Dialog", "Chicky"))
        self.label_55.setText(_translate("Dialog", "Thông tin thanh toán"))
        self.label_7.setText(_translate("Dialog", "Chưa có món ăn được thêm:"))
        self.label_9.setText(_translate("Dialog", "Hiện giá tiền:"))
        self.chuyen_khoan.setText(_translate("Dialog", "Chuyển khoản"))
        self.tien_mat.setText(_translate("Dialog", "Tiền mặt"))
        self.xac_nhan.setText(_translate("Dialog", "Xác nhận"))
        self.chon_ban.setItemText(0, _translate("Dialog", "Bàn"))
        self.chon_ban.setItemText(1, _translate("Dialog", "Bàn 1"))
        self.chon_ban.setItemText(2, _translate("Dialog", "Bàn 2"))
        self.chon_ban.setItemText(3, _translate("Dialog", "Bàn 3"))
        self.chon_ban.setItemText(4, _translate("Dialog", "Bàn 4"))
        self.chon_ban.setItemText(5, _translate("Dialog", "Bàn 5"))
        self.chon_ban.setItemText(6, _translate("Dialog", "Bàn 6"))
        self.chon_ban.setItemText(7, _translate("Dialog", "Bàn 7"))
        self.chon_ban.setItemText(8, _translate("Dialog", "Bàn 8"))
        self.chon_ban.setItemText(9, _translate("Dialog", "Bàn 9"))
        self.chon_ban.setItemText(10, _translate("Dialog", "Bàn 10"))
        self.chon_ban.setItemText(11, _translate("Dialog", "Bàn 11"))
        self.chon_ban.setItemText(12, _translate("Dialog", "Bàn 12"))
import doan_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
