# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'man_hinh_chinh_sau_khi_dang_nhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1220, 798)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 120, 221, 681))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: #C62828\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.mon_an = QtWidgets.QPushButton(Dialog)
        self.mon_an.setGeometry(QtCore.QRect(-10, 120, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mon_an.setFont(font)
        self.mon_an.setStyleSheet("")
        self.mon_an.setObjectName("mon_an")
        self.gio_hang = QtWidgets.QPushButton(Dialog)
        self.gio_hang.setGeometry(QtCore.QRect(-10, 210, 231, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.gio_hang.setFont(font)
        self.gio_hang.setStyleSheet("")
        self.gio_hang.setObjectName("gio_hang")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 91, 91))
        self.label_4.setStyleSheet("border-image: url(:/pic/logoss.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.tim_kiem = QtWidgets.QLineEdit(Dialog)
        self.tim_kiem.setGeometry(QtCore.QRect(360, 40, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tim_kiem.setFont(font)
        self.tim_kiem.setStyleSheet("QLineEdit {\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"    background-color: #f9f9f9;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid white;  /* vẫn là trắng khi focus */\n"
"}\n"
"")
        self.tim_kiem.setText("")
        self.tim_kiem.setObjectName("tim_kiem")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: transparent;  /* làm nền trong suốt nếu muốn */            /* tùy chỉnh cỡ chữ nếu cần */\n"
"    font-weight: bold;              /* chữ đậm */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1231, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #D32F2F\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 120, 1001, 681))
        self.label_6.setStyleSheet("border-image: url(:/pic/ChatGPT Image 09_39_07 24 thg 4, 2025.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.mon_an.raise_()
        self.gio_hang.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.tim_kiem.raise_()
        self.label_6.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mon_an.setText(_translate("Dialog", "🍰Menu món ăn "))
        self.gio_hang.setText(_translate("Dialog", "🛒Giỏ hàng"))
        self.tim_kiem.setPlaceholderText(_translate("Dialog", "Tìm kiếm..."))
        self.label_3.setText(_translate("Dialog", "Chicky"))
import doan_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
