# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1220, 801)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 120, 221, 681))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: #C62828\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.mon_an = QtWidgets.QPushButton(Dialog)
        self.mon_an.setGeometry(QtCore.QRect(-10, 120, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mon_an.setFont(font)
        self.mon_an.setStyleSheet("")
        self.mon_an.setObjectName("mon_an")
        self.gio_hang = QtWidgets.QPushButton(Dialog)
        self.gio_hang.setGeometry(QtCore.QRect(-10, 210, 231, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.gio_hang.setFont(font)
        self.gio_hang.setStyleSheet("")
        self.gio_hang.setObjectName("gio_hang")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 91, 91))
        self.label_4.setStyleSheet("border-image: url(:/pic/logoss.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.tim_kiem = QtWidgets.QLineEdit(Dialog)
        self.tim_kiem.setGeometry(QtCore.QRect(360, 40, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tim_kiem.setFont(font)
        self.tim_kiem.setStyleSheet("QLineEdit {\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"    background-color: #f9f9f9;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid white;  /* vẫn là trắng khi focus */\n"
"}\n"
"")
        self.tim_kiem.setText("")
        self.tim_kiem.setObjectName("tim_kiem")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: transparent;  /* làm nền trong suốt nếu muốn */            /* tùy chỉnh cỡ chữ nếu cần */\n"
"    font-weight: bold;              /* chữ đậm */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1231, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #D32F2F")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 120, 1001, 681))
        self.label_6.setStyleSheet("background-color: rgb(255, 245, 225);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_55 = QtWidgets.QLabel(Dialog)
        self.label_55.setGeometry(QtCore.QRect(620, 160, 181, 61))
        self.label_55.setStyleSheet("QLabel {\n"
"    background-color: #d2b48c;  /* Nâu nhạt (beige) */\n"
"    color: #4e342e;              /* Nâu đậm cho chữ */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    border-radius: 12px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.label_55.setObjectName("label_55")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(630, 720, 175, 43))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_111 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_111.setObjectName("horizontalLayout_111")
        self.horizontalLayout_112 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_112.setObjectName("horizontalLayout_112")
        self.page1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.page1.setFont(font)
        self.page1.setStyleSheet("QPushButton {\n"
"    width: 35px;            /* Chiều rộng của button */\n"
"    height: 35px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,255,255);\n"
"    color: black;            /* Màu chữ */\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(220,220,220);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.page1.setObjectName("page1")
        self.horizontalLayout_112.addWidget(self.page1)
        self.horizontalLayout_111.addLayout(self.horizontalLayout_112)
        self.horizontalLayout_113 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_113.setObjectName("horizontalLayout_113")
        self.page2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page2.setFont(font)
        self.page2.setStyleSheet("QPushButton {\n"
"    width: 35px;            /* Chiều rộng của button */\n"
"    height: 35px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,255,255);\n"
"    color: black;            /* Màu chữ */\n"
"border: 1.5px solid black;   /* Viền đen, dày 2px */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:   rgb(220,220,220);;; /* Màu nền khi hover */\n"
"}\n"
"")
        self.page2.setObjectName("page2")
        self.horizontalLayout_113.addWidget(self.page2)
        self.horizontalLayout_111.addLayout(self.horizontalLayout_113)
        self.horizontalLayout_114 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_114.setObjectName("horizontalLayout_114")
        self.page3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page3.setFont(font)
        self.page3.setStyleSheet("QPushButton {\n"
"    width: 35px;            /* Chiều rộng của button */\n"
"    height: 35px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,255,255);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(220,220,220);;; /* Màu nền khi hover */\n"
"}\n"
"")
        self.page3.setObjectName("page3")
        self.horizontalLayout_114.addWidget(self.page3)
        self.horizontalLayout_111.addLayout(self.horizontalLayout_114)
        self.horizontalLayout_115 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_115.setObjectName("horizontalLayout_115")
        self.page4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page4.setFont(font)
        self.page4.setStyleSheet("QPushButton {\n"
"    width: 35px;            /* Chiều rộng của button */\n"
"    height: 35px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,255,255);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:   rgb(220,220,220);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.page4.setObjectName("page4")
        self.horizontalLayout_115.addWidget(self.page4)
        self.horizontalLayout_111.addLayout(self.horizontalLayout_115)
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(510, 480, 170, 170))
        self.label_33.setStyleSheet("border-image: url(:/pic/khoai_tay_lac.jpg);\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */\n"
"\n"
"\n"
"")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_56 = QtWidgets.QLabel(Dialog)
        self.label_56.setGeometry(QtCore.QRect(290, 430, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Dialog)
        self.label_57.setGeometry(QtCore.QRect(520, 430, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setWordWrap(True)
        self.label_57.setObjectName("label_57")
        self.label_66 = QtWidgets.QLabel(Dialog)
        self.label_66.setGeometry(QtCore.QRect(990, 260, 170, 170))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("border-image: url(:/pic/khoai_tay_vua.png);\n"
"\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */")
        self.label_66.setText("")
        self.label_66.setObjectName("label_66")
        self.khoai_tay_chien_vua_20k = QtWidgets.QPushButton(Dialog)
        self.khoai_tay_chien_vua_20k.setGeometry(QtCore.QRect(1130, 440, 25, 25))
        self.khoai_tay_chien_vua_20k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.khoai_tay_chien_vua_20k.setObjectName("khoai_tay_chien_vua_20k")
        self.label_64 = QtWidgets.QLabel(Dialog)
        self.label_64.setGeometry(QtCore.QRect(760, 650, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setWordWrap(True)
        self.label_64.setObjectName("label_64")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(750, 480, 170, 170))
        self.label_34.setStyleSheet("border-image: url(:/pic/khoai_chien_trung_muoi.jpg);\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */\n"
"\n"
"\n"
"")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_61 = QtWidgets.QLabel(Dialog)
        self.label_61.setGeometry(QtCore.QRect(520, 650, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.label_63 = QtWidgets.QLabel(Dialog)
        self.label_63.setGeometry(QtCore.QRect(750, 260, 170, 170))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("border-image: url(:/pic/banh_mi_ga_chien.png);\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */")
        self.label_63.setText("")
        self.label_63.setObjectName("label_63")
        self.khoai_lac_pho_mai_25k = QtWidgets.QPushButton(Dialog)
        self.khoai_lac_pho_mai_25k.setGeometry(QtCore.QRect(650, 660, 25, 25))
        self.khoai_lac_pho_mai_25k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.khoai_lac_pho_mai_25k.setObjectName("khoai_lac_pho_mai_25k")
        self.label_65 = QtWidgets.QLabel(Dialog)
        self.label_65.setGeometry(QtCore.QRect(1000, 430, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setWordWrap(True)
        self.label_65.setObjectName("label_65")
        self.khoai_chien_trung_muoi_27k = QtWidgets.QPushButton(Dialog)
        self.khoai_chien_trung_muoi_27k.setGeometry(QtCore.QRect(890, 660, 25, 25))
        self.khoai_chien_trung_muoi_27k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.khoai_chien_trung_muoi_27k.setObjectName("khoai_chien_trung_muoi_27k")
        self.hamburger_pho_mai_45k = QtWidgets.QPushButton(Dialog)
        self.hamburger_pho_mai_45k.setGeometry(QtCore.QRect(420, 440, 25, 25))
        self.hamburger_pho_mai_45k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.hamburger_pho_mai_45k.setObjectName("hamburger_pho_mai_45k")
        self.hamburger_ga_nuong_44k = QtWidgets.QPushButton(Dialog)
        self.hamburger_ga_nuong_44k.setGeometry(QtCore.QRect(650, 440, 25, 25))
        self.hamburger_ga_nuong_44k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.hamburger_ga_nuong_44k.setObjectName("hamburger_ga_nuong_44k")
        self.label_62 = QtWidgets.QLabel(Dialog)
        self.label_62.setGeometry(QtCore.QRect(760, 430, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setWordWrap(True)
        self.label_62.setObjectName("label_62")
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(510, 260, 170, 170))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("border-image: url(:/pic/hamburger_ga_nuong.png);\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */")
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.ga_ran_phu_sot_pho_mai_45k = QtWidgets.QPushButton(Dialog)
        self.ga_ran_phu_sot_pho_mai_45k.setGeometry(QtCore.QRect(1130, 660, 25, 25))
        self.ga_ran_phu_sot_pho_mai_45k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.ga_ran_phu_sot_pho_mai_45k.setObjectName("ga_ran_phu_sot_pho_mai_45k")
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setGeometry(QtCore.QRect(990, 480, 170, 170))
        self.label_35.setStyleSheet("border-image: url(:/pic/ga_ran_phu_sot_pho_mai.jpg);\n"
"\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */\n"
"\n"
"\n"
"")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.khoai_tay_chien_lon_28k = QtWidgets.QPushButton(Dialog)
        self.khoai_tay_chien_lon_28k.setGeometry(QtCore.QRect(420, 660, 25, 25))
        self.khoai_tay_chien_lon_28k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.khoai_tay_chien_lon_28k.setObjectName("khoai_tay_chien_lon_28k")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(280, 480, 170, 170))
        self.label_32.setStyleSheet("border-image: url(:/pic/khoai_tay_lon.png);\n"
"\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */\n"
"\n"
"\n"
"")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(290, 650, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setWordWrap(True)
        self.label_59.setObjectName("label_59")
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setGeometry(QtCore.QRect(280, 260, 170, 170))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("border-image: url(:/pic/hamburger_ga_pho_mai.jpg);\n"
"\n"
"    border-radius: 20px;  /* bạn có thể chỉnh độ bo tùy ý */")
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.label_67 = QtWidgets.QLabel(Dialog)
        self.label_67.setGeometry(QtCore.QRect(1000, 650, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setWordWrap(True)
        self.label_67.setObjectName("label_67")
        self.banh_mi_ga_chien_30k = QtWidgets.QPushButton(Dialog)
        self.banh_mi_ga_chien_30k.setGeometry(QtCore.QRect(890, 440, 25, 25))
        self.banh_mi_ga_chien_30k.setStyleSheet("QPushButton {\n"
"    width: 25px;            /* Chiều rộng của button */\n"
"    height: 25px;           /* Chiều cao của button */\n"
"    border-radius: 5px;      /* Để không bo tròn góc */\n"
"    background-color: rgb(255,140,0);\n"
"    color: black;            /* Màu chữ */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 127);; /* Màu nền khi hover */\n"
"}\n"
"")
        self.banh_mi_ga_chien_30k.setObjectName("banh_mi_ga_chien_30k")
        self.best_seller = QtWidgets.QPushButton(Dialog)
        self.best_seller.setGeometry(QtCore.QRect(1050, 170, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.best_seller.setFont(font)
        self.best_seller.setStyleSheet("QPushButton {\n"
"    background-color: #FF4500;\n"
"    color: white;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  #CC3700\n"
"}\n"
"")
        self.best_seller.setObjectName("best_seller")
        self.label_5.raise_()
        self.mon_an.raise_()
        self.gio_hang.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.tim_kiem.raise_()
        self.label_6.raise_()
        self.label_55.raise_()
        self.horizontalLayoutWidget_8.raise_()
        self.label_33.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_66.raise_()
        self.khoai_tay_chien_vua_20k.raise_()
        self.label_64.raise_()
        self.label_34.raise_()
        self.label_61.raise_()
        self.label_63.raise_()
        self.khoai_lac_pho_mai_25k.raise_()
        self.label_65.raise_()
        self.khoai_chien_trung_muoi_27k.raise_()
        self.hamburger_pho_mai_45k.raise_()
        self.hamburger_ga_nuong_44k.raise_()
        self.label_62.raise_()
        self.label_60.raise_()
        self.ga_ran_phu_sot_pho_mai_45k.raise_()
        self.label_35.raise_()
        self.khoai_tay_chien_lon_28k.raise_()
        self.label_32.raise_()
        self.label_59.raise_()
        self.label_58.raise_()
        self.label_67.raise_()
        self.banh_mi_ga_chien_30k.raise_()
        self.best_seller.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mon_an.setText(_translate("Dialog", "🍰Menu món ăn "))
        self.gio_hang.setText(_translate("Dialog", "🛒Giỏ hàng"))
        self.tim_kiem.setPlaceholderText(_translate("Dialog", "Tìm kiếm..."))
        self.label_3.setText(_translate("Dialog", "Chicky"))
        self.label_55.setText(_translate("Dialog", "Menu"))
        self.page1.setText(_translate("Dialog", "1"))
        self.page2.setText(_translate("Dialog", "2"))
        self.page3.setText(_translate("Dialog", "3"))
        self.page4.setText(_translate("Dialog", "4"))
        self.label_56.setText(_translate("Dialog", "Hamburger phô mai 45K"))
        self.label_57.setText(_translate("Dialog", "Hamburger gà nướng 44K"))
        self.khoai_tay_chien_vua_20k.setText(_translate("Dialog", "+"))
        self.label_64.setText(_translate("Dialog", "Khoai chiên trứng muối 27K"))
        self.label_61.setText(_translate("Dialog", "Khoai lắc phô mai 25K"))
        self.khoai_lac_pho_mai_25k.setText(_translate("Dialog", "+"))
        self.label_65.setText(_translate("Dialog", "Khoai tây chiên vừa 20K"))
        self.khoai_chien_trung_muoi_27k.setText(_translate("Dialog", "+"))
        self.hamburger_pho_mai_45k.setText(_translate("Dialog", "+"))
        self.hamburger_ga_nuong_44k.setText(_translate("Dialog", "+"))
        self.label_62.setText(_translate("Dialog", "Bánh mì gà chiên 30K"))
        self.ga_ran_phu_sot_pho_mai_45k.setText(_translate("Dialog", "+"))
        self.khoai_tay_chien_lon_28k.setText(_translate("Dialog", "+"))
        self.label_59.setText(_translate("Dialog", "Khoai tây chiên lớn 28K"))
        self.label_67.setText(_translate("Dialog", "Gà rán phủ sốt phô mai 45K"))
        self.banh_mi_ga_chien_30k.setText(_translate("Dialog", "+"))
        self.best_seller.setText(_translate("Dialog", "Best Seller🔥"))
import doan_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
